#!/bin/bash

version='1.0.0'
bakfile=/home/adnanhd/.all.hosts.bak
tmpfile=/tmp/.all.hosts.tmp
hstfile=/etc/all.hosts.cfg
lockfile=/home/adnanhd/.all.hosts.lock
verbose=0

if [ ! -f $lockfile ]; then
	sudo iptables-save > $bakfile
	touch $lockfile
fi
rm -f $tmpfile

for i in $(cat $hstfile); do
	getent ahosts $i | awk '{ print $1 }' | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' >> $tmpfile
done

sudo iptables -F INPUT
sudo iptables -F OUTPUT
sudo iptables -F FORWARD

sudo iptables -P INPUT DROP
sudo iptables -P OUTPUT DROP
sudo iptables -P FORWARD DROP

for ip in $(cat $tmpfile | uniq); do
	sudo iptables -A INPUT -s $ip
	sudo iptables -A OUTPUT -s $ip
	sudo iptables -A FORWARD -s $ip
done

